[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Remappings are defined in remappings.txt

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
